
CREATE TABLE Purchases (ID INT PRIMARY KEY NOT NULL,
ID_Customer INT FOREIGN KEY REFERENCES Customers(ID) NOT NULL,
ID_Artist INT FOREIGN KEY REFERENCES Artists(ID) NOT NULL,
ID_Artwork INT FOREIGN KEY REFERENCES Artworks(ID) NOT NULL,
DateOfPurchase date);
